"""
Discord Token Helper
This script provides instructions for safely extracting your Discord token.
"""

def show_token_instructions():
    """Display step-by-step instructions for getting Discord token"""
    print("🔑 How to Get Your Discord Token")
    print("=" * 40)
    print()
    print("⚠️  SECURITY WARNING:")
    print("   Your Discord token gives FULL ACCESS to your account!")
    print("   Never share it with anyone or post it online.")
    print("   Keep it as secure as your password.")
    print()
    print("📋 Step-by-Step Instructions:")
    print()
    print("1. 🌐 Open Discord in your WEB BROWSER")
    print("   - Go to https://discord.com (NOT the desktop app)")
    print("   - Log in to your account")
    print()
    print("2. 🔧 Open Developer Tools")
    print("   - Windows/Linux: Press F12 or Ctrl+Shift+I")
    print("   - Mac: Press Cmd+Option+I")
    print("   - Or right-click anywhere and select 'Inspect Element'")
    print()
    print("3. 📱 Navigate to Application Tab")
    print("   - Click on the 'Application' tab (top of developer tools)")
    print("   - If you don't see it, look for '>>' and find it there")
    print()
    print("4. 🗂️ Find Local Storage")
    print("   - In the left sidebar, expand 'Local Storage'")
    print("   - Click on 'https://discord.com'")
    print()
    print("5. 🔍 Locate Your Token")
    print("   - In the main area, look for a key named 'token'")
    print("   - The value column contains your token")
    print("   - It will look like: mfa.ABC123... or MTN4...")
    print()
    print("6. 📋 Copy the Token")
    print("   - Double-click on the token value to select it")
    print("   - Copy it (Ctrl+C / Cmd+C)")
    print("   - DO NOT include the quotes around it")
    print()
    print("7. ✅ Paste into Configuration")
    print("   - Use this token when the setup asks for it")
    print("   - Or add it to your .env file as DISCORD_TOKEN=your_token_here")
    print()
    print("🔒 Security Tips:")
    print("   • Never share this token with anyone")
    print("   • Don't post it in Discord, GitHub, or anywhere public")
    print("   • If you think it's compromised, change your Discord password")
    print("   • Close the developer tools when you're done")
    print()
    print("❓ Troubleshooting:")
    print("   • If you don't see 'token' in Local Storage, try refreshing Discord")
    print("   • Make sure you're using discord.com, not the desktop app")
    print("   • The token might be under 'Session Storage' instead")
    print()


def show_guild_id_instructions():
    """Display instructions for getting Guild ID"""
    print("\n🏠 How to Get Server (Guild) ID")
    print("=" * 35)
    print()
    print("1. 🔧 Enable Developer Mode")
    print("   - In Discord, click the gear icon (User Settings)")
    print("   - Go to 'Advanced' in the left sidebar")
    print("   - Turn ON 'Developer Mode'")
    print()
    print("2. 📋 Copy Server ID")
    print("   - Go to the server you want to summarize")
    print("   - Right-click on the server name (at the top)")
    print("   - Select 'Copy Server ID' from the menu")
    print()
    print("3. ✅ Use the ID")
    print("   - Paste this ID when the setup asks for Guild ID")
    print("   - It will be a long number like: 123456789012345678")
    print()


def show_safety_reminders():
    """Show important safety reminders"""
    print("\n🛡️ Important Safety Reminders")
    print("=" * 35)
    print()
    print("✅ What this tool does:")
    print("   • Reads messages from servers you're already in")
    print("   • Processes them locally with AI")
    print("   • Creates summaries on your computer")
    print("   • Never sends data to external services")
    print()
    print("❌ What this tool does NOT do:")
    print("   • Send messages or interact with Discord")
    print("   • Share your data with anyone")
    print("   • Modify or delete anything")
    print("   • Work with servers you're not a member of")
    print()
    print("⚖️ Legal and Ethical Use:")
    print("   • Only use this on servers where you're a legitimate member")
    print("   • Respect Discord's Terms of Service")
    print("   • Don't use this to bypass access controls")
    print("   • Be considerate of other users' privacy")
    print("   • Use the summaries responsibly")
    print()


def main():
    print("🔧 Discord Day Summarizer - Token Helper")
    print("=" * 50)
    
    show_token_instructions()
    show_guild_id_instructions()
    show_safety_reminders()
    
    print("\n🎉 Ready to proceed!")
    print("Now run: python setup.py")
    print()
    input("Press Enter to exit...")


if __name__ == "__main__":
    main()
